using System;
using UnityEngine;
using UnityEngine.UI;

public class CompletedMenu : MonoBehaviour
{
    public static string PrevLevel;
    public static bool LastLevel;
    public static float Time;

    void Start()
    {
        Game.LevelCompleted();

        Text timeText = GameObject.Find("/Canvas/Time").GetComponent<Text>();
        timeText.text += "<color=yellow>" + String.Format("{0:F1}/{1:F1}", Time, Game.TimeLimit) + "</color>";

        Text pointsText = GameObject.Find("/Canvas/Points").GetComponent<Text>();
        pointsText.text += "<color=yellow>" + Game.Points + "/" + Game.MaxPoints + "</color>";

        if (LastLevel)
        {
            Text nextText = GameObject.Find("/Canvas/Next").GetComponent<Text>();
            nextText.GetComponent<Renderer>().enabled = false;

            Text menuText = GameObject.Find("/Canvas/Menu").GetComponent<Text>();
            menuText.transform.position = new Vector3(0, -76, 0);
        }
    }

    public void NextClick()
    {
        if (Game.AutoGenerated)
        {
            LevelGenerator.cubes = (ushort)(LevelGenerator.cubes * 1.5F);
            Game.GenerateGame();
        }
        else
        {
            if (LastLevel)
                Application.LoadLevel("MenuScene");
            else
            {
                Game.LoadLevel();
            }
        }
    }
    public void MenuClick()
    {
        Application.LoadLevel("MenuScene");
    }
}
